---
- hosts: localhost
  connection: local
  gather_facts: false

  vars_prompt:

    - name: dt_tenant
      prompt: What is your DT environment (no trailing slash eg. https://abc12345.live.dynatrace.com)?
      private: false

    - name: dt_api_token
      prompt: What is your DT API Token?
      private: false

    - name: deployment_version
      prompt: What is the deployment version number (eg. v0.0.2)?
      private: false

    - name: releaser_name
      prompt: What is your name?
      private: false

    - name: releaser_email
      prompt: What is your email?
      private: false

    - name: approver_name
      prompt: Who approved this release (someone other than you)?
      private: false

    - name: approver_email
      prompt: What is the approvers email address?
      private: false

    - name: emergency_contact_name
      prompt: Who is the emergency contact person (not you or the approver)?
      private: false
    
    - name: emergency_contact_number
      prompt: What is the phone number for the emergency contact?
      private: false

    - name: ticket_number
      prompt: What is the ticket number of the approval (eg. TEST001)?
      private: false

  tasks:

  - name: "Sending Release Event to DT"
    ansible.builtin.uri:
      url: "{{ dt_tenant }}/api/v1/events"
      method: POST
      status_code: 200
      body_format: json
      headers:
        Authorization: "Api-token {{dt_api_token}}"
      body: >-
        {
          "eventType": "CUSTOM_DEPLOYMENT",
          "timeout": 5,
          "attachRules": {
            "tagRule": [{
              "meTypes": [ "HOST" ],
              "tags": [{
                "context": "CONTEXTLESS",
                "key": "at-host-group",
                "value": "at-demo-enrichment"
              }]
            }]
          },
          "source": "Ansible",
          "deploymentName": "{{ deployment_version}} deployment by {{ releaser_name}}",
          "deploymentVersion": "{{ deployment_version}}",
          "customProperties": {
            "deployment version": "{{ deployment_version}}",
            "operator": "{{ releaser_name }}",
            "operator email": "{{ releaser_email }}",
            "approver": "{{ approver_name }}",
            "approver email": "{{ approver_email }}",
            "escalation contact": "{{ emergency_contact_name }}",
            "escalation contact number": "{{ emergency_contact_number }}",
            "ticket number": "{{ ticket_number }}",
            "ticket link": "https://myTicketSystem.com/{{ticket_number}}"
          }
        }

  - name: "Running Release (Press Ctrl + C to end when you see a problem in Dynatrace)"
    ansible.builtin.shell:
      cmd: "stress -c 1 -t 5m"